### PR TITLE
Read me update

### PR DESCRIPTION
**Pull request by Adamj1232**
## What's this PR do?

I reworked the read me file to give more background about my experience and for enhanced direction for the user

## Pre-Merge TODOs
 - [ ] Screenshots Included
    - ANY change to the UI of the app must have screenshots/gifs
    - Hint: recordit is really great for this
 - [ ] Tests Added
   - ANY change that can be tested must include testing
 - [x] Updated Documentation
   - Update your README if any new dependencies are added
 - [ ] Add follow up issues?
 - [ ] 2 PR reviews completed

## Learning

I used recordIt to create a gif of my app, that was pretty cool

## Where should the reviewer start?

Readme file

### CODE REVIEW

**Comment by kamos1** [comment]
@Adamj1232 the readme looks good. The reflection does a good job of describing how you got the app off the ground.

**Comment by jbevis** [comment]
Adam, the app and the readme look really good, the updates provide a lot more insight into your approach to the project and what purpose it serves. The gif link does appear to be broken though.

**Comment by Adamj1232** [comment]
Fixed the gif, thanks JACK!

**Comment by Adamj1232** [comment]
@joshuajhun @Tman22 or @rrgayhart
Have had two people review my readme and give some excellent comments about how I can improve it.

**Pull request merged**
